---
- hosts: all
  become: true
  tasks:
    - name: Installer les dépendances nécessaires
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Ajouter la clé GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Installer Docker
      apt:
        name: docker-ce
        state: present

    - name: Ajouter l'utilisateur actuel au groupe Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Démarrer le service Docker
      service:
        name: docker
        state: started
